### ISSUE TITLE
Inspection date is displayed incorrectly on the property cards on the Open Home page

### ISSUE THREAD

**Issue by jessqnnguyen** [lukekaalim/lemon-lime#10]
# Inspection date is displayed incorrectly on the property cards on the Open Home page
The date displayed on the property cards on the Open Homes page  is incorrect by a month..some kind of counter error again? It is inconsistent across the page.

## How to reproduce the bug?
1. From the  homepage, select Buy (top navigation bar) > Open Homes. 
2. Scroll down to see the open homes information for each property.  
3. In the property information box (between the photo and the map) , the date is incorrectly displayed.  
 
## Relevant screenshots

Note it is displayed correctly on the calendar and the heading below the calendar but not on each property card itself. Looks like it only affects the property cards.
![open-homes-page](https://cloud.githubusercontent.com/assets/4889102/23889051/36f87e04-08df-11e7-9930-98780099b418.png)

**Comment by lukekaalim** [comment]
since the dates are stored in unix time, it is possible that the cards resolve the dates with the incorrect time zone.

**Comment by jessqnnguyen** [comment]
Hm how does that work though? Are there time zones that are a month behind? That sounds a bit strange.

**Comment by lukekaalim** [comment]
Oh wait, you're right, I've commented on the wrong issue

**Comment by lukekaalim** [comment]
my bad

**Comment by jessqnnguyen** [comment]
Haha yeah I was thinking you might have meant to comment on the other thread.

Anyway so I was looking at the code - lemon-lime/resources/views/static/open-homes.blade.php:
What file populates the inspection variable in this file?

**Comment by lukekaalim** [comment]
We get the inspection JSON dynamically inserted into the page when it's generated, but the display is populated live from javascript

**Comment by lukekaalim** [comment]
Wait, I solved it. Yeah, it was something stupid on my end.
Date.getMonth() is zero indexed

**Comment by jessqnnguyen** [comment]
Okay cool yeah that's what I thought, btw what file is that?

**Comment by lukekaalim** [comment]
Just for reference, the javascript is in the bottom of the file, in the ('inline-script') section.
the {!! json_encode($inspections) !!}; there is some php injection

**Comment by lukekaalim** [comment]
I'll push a fix for it in a sec

**Comment by jessqnnguyen** [comment]
Ahh I see found it, thanks Okay yeah that's interesting - thought it was an indexing error!

**Comment by jessqnnguyen** [comment]
Great I'll assign this issue to you

**Comment by lukekaalim** [comment]
852e41390aad6220c2ce73f7bbe9ebdcaa1531fe should solve this

**Comment by lukekaalim** [comment]
should be fixed on live now
