### ISSUE TITLE
Available date on listings is incorrectly displayed

### ISSUE THREAD

**Issue by jessqnnguyen** [lukekaalim/lemon-lime#8]
# Available date on listings is incorrectly displayed on listing pages. 
The available date on all listings is incorrectly displayed on rental (may affect sales too - to confirm) listing pages - it's one day behind of the selected date on the admin.  

## How to reproduce (one example)
1. From the  homepage, select navbar > Rent > Houses for Rent. 
2. Select the listing '2 Lucinda Ave, Killarney Vale`. 
3. In the property information box on the top right hand side, the available date is incorrectly displayed.  

### Expected result
The available date here is supposed to be on the 29th March, 2017.

### Actual result
Date displayed is 28th March 2017.

## Relevant screenshots
Available date shown is 28th March
![listing-page](https://puu.sh/uHJGP/3ace15d689.png)

Available date selected from admin is 29th March
![admin-page](https://puu.sh/uHJWP/24b345ca05.png)

**Comment by jessqnnguyen** [comment]
@lukekaalim this should be a quick fix? Sounds like some kind a increment error?

**Comment by lukekaalim** [comment]
since the dates are stored in unix time, it is possible that the cards resolve the dates with the incorrect time zone.

**Comment by lukekaalim** [comment]
should be fixed on live now
